---
exclude: docs/|ext/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
        name: Check that merge conflicts are not being committed
      - id: debug-statements
        name: Detect accidentally committed debug statements
      - id: check-builtin-literals
        name: Require literal syntax when initializing builtin types
        exclude: ^.*/.*_vendor/
      - id: detect-private-key
        name: Detect if private key is added to the repository
        exclude: ^docs/apache-airflow-providers-ssh/connections/ssh.rst$
      - id: end-of-file-fixer
        name: Make sure that there is an empty line at the end
      - id: mixed-line-ending
        name: Detect if mixed line ending is used (\r vs. \r\n)
      - id: trailing-whitespace
        name: Remove trailing whitespace at end of line
      - id: fix-encoding-pragma
        name: Remove encoding header from Python files
        args:
          - --remove
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        name: Check YAML files with yamllint
        entry: yamllint
        types:
          - yaml
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        name: Run black on Python code blocks in documentation files
        args:
          - --line-length=110
          - --target-version=py37
          - --target-version=py38
          - --target-version=py39
          - --target-version=py310
        alias: blacken-docs
        additional_dependencies:
          - black==23.10.0
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
